// 推箱子 (Sokoban) state controller: owns board state, undo stack, timer,
// win detection, persistence. No DOM access here (that's ui.js's job).
//
// Levels are generated by reverse play ("pulling" boxes) starting from an
// already-solved arrangement (every box on a target), the same guaranteed-
// solvable-by-construction technique used for klotski/js/game.js's board
// scrambling, adapted to Sokoban's push/pull mechanics: a push moves the
// player into a box's cell and the box one further cell in the same
// direction; a pull is its exact inverse (player steps backward, box moves
// into the cell the player just vacated). Any sequence of legal pulls can
// therefore always be undone by the corresponding sequence of pushes,
// guaranteeing a solution exists — regardless of how the player chooses to
// actually solve it.
var SokobanGame = (function () {
  const DIRS = [
    { dr: -1, dc: 0 },
    { dr: 1, dc: 0 },
    { dr: 0, dc: -1 },
    { dr: 0, dc: 1 },
  ];

  // Board sizes matter more than they might look: a pull needs two clear
  // cells beyond the box in a straight line, so a box near the center of a
  // small interior can have *zero* legal pull directions (a 3x3 interior —
  // the old 5x5 board's — leaves a dead center with no pull possible at
  // all in any direction). Minimums bumped up so pull-generation actually
  // has room to work; verified empirically (see game history) rather than
  // derived purely on paper.
  const TIERS = {
    easy: { rows: 6, cols: 6, boxCount: 1, interiorWalls: 1, pullSteps: 6 },
    medium: { rows: 7, cols: 7, boxCount: 2, interiorWalls: 3, pullSteps: 12 },
    hard: { rows: 8, cols: 8, boxCount: 3, interiorWalls: 5, pullSteps: 18 },
    expert: { rows: 9, cols: 9, boxCount: 4, interiorWalls: 7, pullSteps: 26 },
  };

  let state = null;
  let timerInterval = null;
  let changeListener = null;

  function onChange(cb) {
    changeListener = cb;
  }
  function notify(event) {
    if (changeListener) changeListener(state, event || null);
  }

  function tierFor(difficulty) {
    return TIERS[difficulty] || TIERS.easy;
  }

  function shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const tmp = arr[i];
      arr[i] = arr[j];
      arr[j] = tmp;
    }
    return arr;
  }

  function key(r, c) {
    return r + "," + c;
  }

  function isWallAt(walls, rows, cols, r, c) {
    if (r < 0 || r >= rows || c < 0 || c >= cols) return true;
    return walls.has(key(r, c));
  }

  // -- level generation -----------------------------------------------------
  function isConnected(walls, rows, cols) {
    let start = null;
    for (let r = 1; r < rows - 1 && !start; r++) {
      for (let c = 1; c < cols - 1; c++) {
        if (!walls.has(key(r, c))) {
          start = { r, c };
          break;
        }
      }
    }
    if (!start) return true;
    const seen = new Set([key(start.r, start.c)]);
    const queue = [start];
    while (queue.length) {
      const cur = queue.pop();
      DIRS.forEach(({ dr, dc }) => {
        const nr = cur.r + dr;
        const nc = cur.c + dc;
        if (nr < 1 || nr >= rows - 1 || nc < 1 || nc >= cols - 1) return;
        const k = key(nr, nc);
        if (walls.has(k) || seen.has(k)) return;
        seen.add(k);
        queue.push({ r: nr, c: nc });
      });
    }
    let totalOpen = 0;
    for (let r = 1; r < rows - 1; r++) {
      for (let c = 1; c < cols - 1; c++) {
        if (!walls.has(key(r, c))) totalOpen++;
      }
    }
    return seen.size === totalOpen;
  }

  function buildWalls(rows, cols, interiorWallCount) {
    const walls = new Set();
    for (let c = 0; c < cols; c++) {
      walls.add(key(0, c));
      walls.add(key(rows - 1, c));
    }
    for (let r = 0; r < rows; r++) {
      walls.add(key(r, 0));
      walls.add(key(r, cols - 1));
    }
    const interiorCells = [];
    for (let r = 1; r < rows - 1; r++) {
      for (let c = 1; c < cols - 1; c++) interiorCells.push({ r, c });
    }
    shuffle(interiorCells);
    let placed = 0;
    for (const cell of interiorCells) {
      if (placed >= interiorWallCount) break;
      const k = key(cell.r, cell.c);
      walls.add(k);
      if (isConnected(walls, rows, cols)) {
        placed++;
      } else {
        walls.delete(k);
      }
    }
    return walls;
  }

  function openInteriorCells(walls, rows, cols) {
    const cells = [];
    for (let r = 1; r < rows - 1; r++) {
      for (let c = 1; c < cols - 1; c++) {
        if (!walls.has(key(r, c))) cells.push({ row: r, col: c });
      }
    }
    return cells;
  }

  // BFS over open, non-wall, non-box cells reachable by walking (no box
  // interaction) from `start`.
  function walkableCells(walls, boxes, rows, cols, start) {
    const boxSet = new Set(boxes.map((b) => key(b.row, b.col)));
    const seen = new Set([key(start.row, start.col)]);
    const result = [start];
    const queue = [start];
    while (queue.length) {
      const cur = queue.pop();
      DIRS.forEach(({ dr, dc }) => {
        const nr = cur.row + dr;
        const nc = cur.col + dc;
        if (isWallAt(walls, rows, cols, nr, nc)) return;
        const k = key(nr, nc);
        if (seen.has(k) || boxSet.has(k)) return;
        seen.add(k);
        const pos = { row: nr, col: nc };
        result.push(pos);
        queue.push(pos);
      });
    }
    return result;
  }

  function isSolvedBoard(boxes, targets) {
    return boxes.every((b) => targets.some((t) => t.row === b.row && t.col === b.col));
  }

  // Returns the set of "r,c" box positions responsible for the puzzle
  // being trivial: any box already on target, plus any box the player
  // could win by pushing right now. Empty set means the puzzle is
  // genuinely non-trivial. Checking (and specifically un-sticking) these
  // exact boxes — not just "is it solved" — is what klotski/js/game.js's
  // equivalent guard had to learn the hard way: a uniformly random escape
  // move can spend every attempt nudging an already-scrambled piece while
  // the trivial one never budges.
  function trivialBoxKeys(walls, boxes, targets, player, rows, cols) {
    const keys = new Set();
    boxes.forEach((box) => {
      if (targets.some((t) => t.row === box.row && t.col === box.col)) {
        keys.add(box.row + "," + box.col);
      }
    });
    boxes.forEach((box, bi) => {
      DIRS.forEach(({ dr, dc }) => {
        if (player.row !== box.row - dr || player.col !== box.col - dc) return;
        const dest = { row: box.row + dr, col: box.col + dc };
        if (isWallAt(walls, rows, cols, dest.row, dest.col)) return;
        if (boxes.some((b, i) => i !== bi && b.row === dest.row && b.col === dest.col)) return;
        const hyp = boxes.map((b, i) => (i === bi ? dest : b));
        if (isSolvedBoard(hyp, targets)) keys.add(box.row + "," + box.col);
      });
    });
    return keys;
  }

  // preferBoxes (optional Set of "r,c" box positions): when given and at
  // least one matching pull is available, only those are considered. Used
  // by the anti-triviality guard below to specifically move whichever
  // box(es) are still sitting on target, rather than a uniformly random
  // pull that might spend every attempt nudging an already-scrambled box
  // while the trivial one never moves (the exact class of bug found and
  // fixed in klotski/js/game.js's equivalent guard).
  function pullOnce(walls, boxes, player, rows, cols, preferBoxes) {
    const walkable = walkableCells(walls, boxes, rows, cols, player);
    const options = [];
    walkable.forEach((pos) => {
      DIRS.forEach(({ dr, dc }) => {
        const boxR = pos.row + dr;
        const boxC = pos.col + dc;
        const behindR = pos.row - dr;
        const behindC = pos.col - dc;
        if (!boxes.some((b) => b.row === boxR && b.col === boxC)) return;
        if (isWallAt(walls, rows, cols, behindR, behindC)) return;
        if (boxes.some((b) => b.row === behindR && b.col === behindC)) return;
        options.push({ from: pos, boxR, boxC, behindR, behindC });
      });
    });
    if (options.length === 0) return player;
    const preferred = preferBoxes
      ? options.filter((o) => preferBoxes.has(o.boxR + "," + o.boxC))
      : [];
    const pool = preferred.length > 0 ? preferred : options;
    const choice = pool[Math.floor(Math.random() * pool.length)];
    const box = boxes.find((b) => b.row === choice.boxR && b.col === choice.boxC);
    box.row = choice.from.row;
    box.col = choice.from.col;
    return { row: choice.behindR, col: choice.behindC };
  }

  function buildLevel(params) {
    const { rows, cols, boxCount, interiorWalls, pullSteps } = params;
    const walls = buildWalls(rows, cols, interiorWalls);
    const open = shuffle(openInteriorCells(walls, rows, cols));
    const targets = open.slice(0, boxCount).map((c) => ({ row: c.row, col: c.col }));
    const boxes = targets.map((t) => ({ row: t.row, col: t.col }));
    const remaining = open.slice(boxCount);
    let player = remaining.length > 0 ? { ...remaining[0] } : { ...open[0] };

    for (let i = 0; i < pullSteps; i++) {
      player = pullOnce(walls, boxes, player, rows, cols);
    }

    // Safety net: don't ship a puzzle that's already solved or one push
    // from solved — keep pulling until it's genuinely a puzzle, preferring
    // each iteration to move whichever box(es) are currently the trivial
    // one(s) (re-computed every iteration, since un-sticking one trivial
    // box can just leave it freshly one-push-from-solved instead — see
    // trivialBoxKeys).
    let guard = 0;
    let trivial = trivialBoxKeys(walls, boxes, targets, player, rows, cols);
    while (trivial.size > 0 && guard < 3000) {
      player = pullOnce(walls, boxes, player, rows, cols, trivial);
      trivial = trivialBoxKeys(walls, boxes, targets, player, rows, cols);
      guard++;
    }

    return { rows, cols, walls, targets, boxes, player, trivial: trivial.size > 0 };
  }

  // Regenerating from scratch (fresh wall/target layout, not just more
  // pulls on the same one) is a cheap, robust final backstop: even in the
  // rare structural configuration where 3000 guard iterations can't shake
  // a box loose, a differently-shaped board almost always can. Each
  // attempt is <1ms, so a handful of retries is imperceptible.
  function buildLevelWithRetry(params) {
    let level = buildLevel(params);
    let attempts = 0;
    while (level.trivial && attempts < 8) {
      level = buildLevel(params);
      attempts++;
    }
    return level;
  }

  // -- lifecycle ------------------------------------------------------------
  function stopTimerInterval() {
    if (timerInterval) {
      clearInterval(timerInterval);
      timerInterval = null;
    }
  }
  function startTimer() {
    state.startTimestamp = Date.now();
    stopTimerInterval();
    timerInterval = setInterval(() => {
      persist();
      notify("tick");
    }, 1000);
  }
  function getElapsedMs() {
    if (!state) return 0;
    if (state.status !== "playing") return state.elapsedMs;
    return state.elapsedMs + (Date.now() - state.startTimestamp);
  }

  function serialize() {
    return {
      difficulty: state.difficulty,
      rows: state.rows,
      cols: state.cols,
      walls: Array.from(state.walls),
      targets: state.targets,
      boxes: state.boxes,
      player: state.player,
      history: state.history,
      moves: state.moves,
      elapsedMs: getElapsedMs(),
      status: state.status === "won" ? "won" : "playing",
    };
  }

  function deserialize(saved) {
    return {
      difficulty: saved.difficulty,
      rows: saved.rows,
      cols: saved.cols,
      walls: new Set(saved.walls || []),
      targets: saved.targets,
      boxes: saved.boxes,
      player: saved.player,
      history: Array.isArray(saved.history) ? saved.history : [],
      moves: saved.moves || 0,
      elapsedMs: saved.elapsedMs || 0,
      startTimestamp: Date.now(),
      status: saved.status === "won" ? "won" : "playing",
    };
  }

  function persist() {
    if (state && state.status !== "won") {
      SokobanStorage.saveCurrentGame(serialize());
    }
  }

  function newGame(difficulty) {
    stopTimerInterval();
    const params = tierFor(difficulty);
    const level = buildLevelWithRetry(params);
    state = {
      difficulty,
      rows: level.rows,
      cols: level.cols,
      walls: level.walls,
      targets: level.targets,
      boxes: level.boxes,
      player: level.player,
      history: [],
      moves: 0,
      elapsedMs: 0,
      startTimestamp: Date.now(),
      status: "playing",
    };
    startTimer();
    persist();
    notify("new-game");
  }

  function resumeGame() {
    const saved = SokobanStorage.loadCurrentGame();
    if (!saved || !Array.isArray(saved.boxes)) return false;
    if (saved.status !== "playing") return false;
    stopTimerInterval();
    state = deserialize(saved);
    if (state.status === "playing") startTimer();
    notify("restore");
    return true;
  }

  function hasSavedResumableGame() {
    const saved = SokobanStorage.loadCurrentGame();
    return !!(saved && saved.status === "playing");
  }

  function hasProgress() {
    if (!state) return false;
    if (state.status !== "playing") return false;
    return state.moves > 0;
  }

  function finishWin() {
    state.elapsedMs = getElapsedMs();
    state.status = "won";
    stopTimerInterval();
    const elapsedSeconds = Math.floor(state.elapsedMs / 1000);
    const isNewBest = SokobanStorage.updateCareer(state.difficulty, elapsedSeconds, state.moves);
    SokobanStorage.appendHistoryEntry({
      difficulty: state.difficulty,
      moves: state.moves,
      elapsedSeconds,
      completedAt: new Date().toISOString(),
    });
    SokobanStorage.clearCurrentGame();
    state.justWon = { isNewBest };
  }

  function move(dr, dc) {
    if (!state || state.status !== "playing") return;
    const nr = state.player.row + dr;
    const nc = state.player.col + dc;
    if (isWallAt(state.walls, state.rows, state.cols, nr, nc)) {
      notify("invalid");
      return;
    }
    const boxIndex = state.boxes.findIndex((b) => b.row === nr && b.col === nc);
    if (boxIndex === -1) {
      state.history.push({ dr, dc, pushedBoxIndex: null });
      state.player = { row: nr, col: nc };
      state.moves++;
      persist();
      notify("move");
      return;
    }
    const br2 = nr + dr;
    const bc2 = nc + dc;
    const blocked =
      isWallAt(state.walls, state.rows, state.cols, br2, bc2) ||
      state.boxes.some((b) => b.row === br2 && b.col === bc2);
    if (blocked) {
      notify("invalid");
      return;
    }
    state.history.push({ dr, dc, pushedBoxIndex: boxIndex });
    state.boxes[boxIndex] = { row: br2, col: bc2 };
    state.player = { row: nr, col: nc };
    state.moves++;
    if (isSolvedBoard(state.boxes, state.targets)) {
      finishWin();
    } else {
      persist();
    }
    notify("push");
  }

  function undo() {
    if (!state || state.status !== "playing" || state.history.length === 0) return;
    const last = state.history.pop();
    state.player = { row: state.player.row - last.dr, col: state.player.col - last.dc };
    if (last.pushedBoxIndex != null) {
      const box = state.boxes[last.pushedBoxIndex];
      state.boxes[last.pushedBoxIndex] = { row: box.row - last.dr, col: box.col - last.dc };
    }
    persist();
    notify("undo");
  }

  function getState() {
    return state;
  }

  function isBoxAt(r, c) {
    return state.boxes.some((b) => b.row === r && b.col === c);
  }
  function isTargetAt(r, c) {
    return state.targets.some((t) => t.row === r && t.col === c);
  }
  function isWallCell(r, c) {
    return state.walls.has(key(r, c));
  }

  function formatTime(ms) {
    if (ms == null) return "--:--";
    const totalSeconds = Math.floor(ms / 1000);
    const m = Math.floor(totalSeconds / 60);
    const s = totalSeconds % 60;
    return String(m).padStart(2, "0") + ":" + String(s).padStart(2, "0");
  }
  function formatSeconds(seconds) {
    return formatTime(seconds == null ? null : seconds * 1000);
  }

  if (typeof window !== "undefined") {
    window.addEventListener("beforeunload", persist);
  }

  return {
    onChange,
    newGame,
    resumeGame,
    hasSavedResumableGame,
    hasProgress,
    getElapsedMs,
    move,
    undo,
    getState,
    isBoxAt,
    isTargetAt,
    isWallCell,
    formatTime,
    formatSeconds,
  };
})();

if (typeof window !== "undefined") {
  window.SokobanGame = SokobanGame;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = SokobanGame;
}
